development:
  adapter: postgresql
  encoding: unicode
  database: work_cafe_development
  pool: 5
  username: walwoodr
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: work_cafe_test
  pool: 5
  username: walwoodr
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: work_cafe_production
  pool: 5
  username: walwoodr
  password:
